name: CI

on:
  push:
    branches:
      - new-index
  pull_request: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang libclang-dev pkg-config
      - name: cargo check
        run: cargo check --all-targets
